### ISSUE TITLE
Calling function via keyboard shortcut: UnoComponent or other way already exiting in unodit?

### ISSUE THREAD

**Issue by jdittrich** [kelsa-pi/unodit#10]
I would like to call functionality of an extension based on unodit code via a keyboard shortcut. 

As far as I understood, shortcuts can only call UnoComponents; Such a component is defined in the main .py file in the `/src` folder by 

    g_ImplementationHelper = unohelper.ImplementationHelper()
    g_ImplementationHelper.addImplementation(ElementFactory,"my.extension.identifier",  ("com.sun.star.task.Job",),)

However, the `ElementFactory` does only implement createUIElement, and does not allow access to properties of the class hierarchy defined in the files in `ui` and `ui_logic`.

Is there any already existing way to trigger extension functionality via a keyboard shortcut?

**Comment by kelsa-pi** [comment]
Not that I’m aware of.

**Comment by jdittrich** [comment]
Thanks. I try to find a way and try to report it back if you are interested.

**Comment by kelsa-pi** [comment]
Please, do. If I can be of assistance, please do not hesitate to contact me.
