### ISSUE TITLE
Question: This package is the new version of Uno-deprecated library to develop the extension?

### ISSUE THREAD

**Issue by RafaelAybar** [kelsa-pi/unodit#11]
In the official web documentation, I have seen links this python library https://github.com/elbow-jason/Uno-deprecated . So, to develop a LibreOffice plugin, in Python, Should I use your library?

**Comment by kelsa-pi** [comment]
Hi, RafaelAybar

I don't know anything about [elbow-jason/Uno-deprecated](https://github.com/elbow-jason/Uno-deprecated).
You can use UNODIT to develop a LibreOffice extension with dialogs. Please read [UNODIT features](https://github.com/kelsa-pi/unodit#features) for more information.
