### ISSUE TITLE
Sidebar install error for minimal example: name 'self' is not defined

### ISSUE THREAD

**Issue by jdittrich** [kelsa-pi/unodit#8]
## Description

 After creating a minimal example and attempting to install the oxt, I get a warning from the extension manager *(com.sun.star.uno.RuntimeException) { { Message = "<class 'NameError'>: name 'self' is not defined,*…

#### Used Software 
* Ubuntu 16.04, Python 3.5.2 (Standard Ubuntu package) 
* Libreoffice 5.3.2.2
* Unodit master as of 12.4.2017 

#### Steps
1. created a minimal example by
    * creating a dialog xdl via the dialog editor in libreoffice
    * putting the path of the xdl in the *config.ini*’s *Panels*- *[Panel1]* section (as value of *xdl_ui*)
    * commenting out the [Panel2], [Panel3] sections of the config.ini (since they don't have a xdl file linked)
    * using `python3 ./unodit.py -m 'sidebar_convert' -d 'JansLibreOfficePath/4/user/Scripts/python/TestLib' -a 'Test_sidebar' -p 1` and subsequent calls with 'sidebar_files' and 'sidebar_oxt'. So I copypasted the commands [from the documentation](https://github.com/kelsa-pi/unodit/wiki/Create-sidebar-extension) and adjusted panel number (-p 1) and the output path (-d)
2. Installation of resulting *.oxt*: After agreeing to the install infobox ("You are about to install…") I get the following error as shown in an extension manager error popup window: `(com.sun.star.uno.RuntimeException) { { Message = "<class 'NameError'>: name 'self' is not defined, traceback follows`[Traceback]

## Comments
I was unable to determine the cause of the error. If you need any further information (pastebin of the trace, resulting .oxt etc.), I can provide it. 

Thanks for writing this, once I get it running, it will be very helpful for me!

**Comment by kelsa-pi** [comment]
Thanks for reporting.

Solved "name 'self' is not defined" problem in master.
There is issue with extension manager. 
Be aware that installation of resulting .oxt on:
`1. Ubuntu: Version: 5.3.2.2 Build ID: 1:5.3.2~rc2-0ubuntu1~xenial0 - NOT WORKING`
`2. Ubuntu: Version: 5.3.2.2 Build ID: libreoffice-5.3.2.2-snap1 - OK`
`3. Ubuntu: Version: 5.3.3.0.0+ Build ID: e57873156d3c04ecc34bb5f38b186ebe29567f0c - OK`
I tested with: Tools - Extension Manager - Add
