### ISSUE TITLE
Trailing slash in output directory causes problems for extension install/uninstall and running

### ISSUE THREAD

**Issue by jdittrich** [kelsa-pi/unodit#9]
If I create my addons using 

`python3 ./unodit.py -m 'sidebar_otx' -d 'myLibreofficePath4/user/Scripts/python/mytestscripts/ ' -a 'Test_sidebar3' -p 1`

The extension installs, but does not run nor properly uninstalls. 

If delete the slash in the -d path and run 

`python3 ./unodit.py -m 'sidebar_otx' -d 'myLibreofficePath4/user/Scripts/python/mytestscripts' -a 'Test_sidebar3' -p 1`

it works.

The only change is 
**…mytestscripts/**  vs. 
**…mytestscripts** 

I think they should not cause  different results – an obvious idea would be cutting off a trailing slash in the path string (but I don't know if that works well across different operating systems)

**Comment by kelsa-pi** [comment]
Hi,

Documentation: https://github.com/kelsa-pi/unodit/wiki/Create-sidebar-extension
For me everything looks correct. What I'm missing?

PS: Extra slash is only in: create project directory in LIBREOFFICE_PATH/4/user/Scripts/python/

**Comment by jdittrich** [comment]
Yes, the documentation is correct. However, it is a very likely error that users put in a trailing slash (like it happened to me) leading to a difficult to un-install extension.

**Comment by kelsa-pi** [comment]
Fixed in master. 
Give it a try.

**Comment by jdittrich** [comment]
Works!
